---
title: "hclust"
author: "brunop31"
date: "16/06/2020"
output: html_document
---
```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(DT)
library(reshape)
library(splitstackshape)
library(ggplot2)
library(scales)
library(ineq)
library(zoo)
library(cluster)
library(corrplot)
library(Hmisc)
library("ggpubr")
library(rstatix)
library(BioStatR)
library(reshape)
library(questionr)
library("FactoMineR")
library("factoextra")
library("gplots")
library(tidyr)
library(plyr)
```

```{r}
pop_2008<-read.csv("pop_2008.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2008" = "Valeur")

pop_2018<-read.csv("pop_2018.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2018" = "Valeur")

prot_ani_hab<-read.csv("prot_ani_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot_ani" = "Valeur")

prot_hab<-read.csv("prot_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot" = "Valeur")

kcal_hab<-read.csv("kcal_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "kcal" = "Valeur")

pib_hab<-read.csv("pib_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "pib" = "Valeur")%>%group_by(Zone)%>%
  summarise_if(is.numeric, round)
```

```{r}
df<-left_join(prot_ani_hab, pop_2008)%>%
  left_join(pop_2018)%>%left_join( prot_hab)%>%
  left_join(kcal_hab)%>%left_join(pib_hab)%>%
  mutate(pop_diff = round((pop2018 - pop2008)*100/pop2008,1),
         prot_ani_prct = round(prot_ani*100/prot,0))%>%
  select(-"prot_ani", -"pop2018", -"pop2008")

sapply(df,function(x) sum(is.na(x)))

na_table<-filter(df, is.na(pop_diff)|is.na(pib))

df["150","pop_diff"]<-	round((41801.53 - 33060)*100/33060,1)
df["35","pib"]<-24971
```

```{r}
df_table<-df
row.names(df_table)<-df_table$Zone
df_table<-select(df_table, -"Zone",-"pib")

df_table.cr<-scale(df_table, center = T, scale = T)

d.df_table<- dist(df_table.cr)

cah.ward <- hclust(d.df_table,method="ward.D2")

plot(cah.ward) 

plot.new()

rect.hclust(cah.ward, k = 10)

groupes.cah <- cutree(cah.ward,k=5)

a<-as.data.frame(sort(groupes.cah))

fviz_dend(cah.ward,
          k = 5,
          cex = 0.2,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 0.8      # Augment the room for labels
          )
```
```{r}
res.pca <- PCA(df_table, graph = FALSE)

fviz_pca_var(res.pca,repel = TRUE)
```

```{r}
groupes<-groupes.cah%>%as.data.frame()

fviz_pca_ind(res.pca, col.ind = as.character(groupes.cah))
```

