---
title: "P5"
author: "brunop31"
date: "15/06/2020"
output: html_document
---
```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(FactoMineR)
library(factoextra)
library(gridExtra)
```


```{r, warning=FALSE, message=FALSE}
pop_2008<-read.csv("pop_2008.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2008" = "Valeur")


pop_2018<-read.csv("pop_2018.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2018" = "Valeur")

prot_ani_hab<-read.csv("prot_ani_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot_ani" = "Valeur")


prot_hab<-read.csv("prot_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot" = "Valeur")

kcal_hab<-read.csv("kcal_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "kcal" = "Valeur")

pib_hab<-read.csv("pib_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "pib" = "Valeur")%>%group_by(Zone)%>%
  summarise_if(is.numeric, round)
```

```{r, warning=FALSE, message=FALSE}
df<-left_join(prot_ani_hab, pop_2008)%>%
  left_join(pop_2018)%>%left_join( prot_hab)%>%
  left_join(kcal_hab)%>%left_join(pib_hab)

sapply(df,function(x) sum(is.na(x)))

na_table<-filter(df, is.na(pop2008)|is.na(pib))

df["138","Zone"]<-"Royaume-Uni"
df["135","Zone"]<-"Corée du Nord"
df["131","Zone"]<-"Corée du Sud"
df["133","Zone"]<-"Laos"
df["168","Zone"]<-"Venezuela"
df["150","pop2008"]<-	33060
df["35","pib"]<-24971

df<-df%>%
  mutate(pop_diff = round((pop2018 -pop2008)*100/pop2008,1),
         prot_ani_prct = round(prot_ani*100/prot,0))%>%
  select(-"prot_ani", -"pop2018", -"pop2008")
```

```{r, warning=FALSE, message=FALSE}
df_table<-df
row.names(df_table)<-df_table$Zone
df_table<-select(df_table, -"Zone",-"pib")

res.pca <- PCA(df_table, graph = FALSE, scale.unit = TRUE, ncp = 3)

summary(res.pca)
```

```{r}
fviz_pca_var(res.pca)
```

```{r}
fviz_pca_ind(res.pca,geom.ind = "point", col.ind = "blue")
```


```{r}
res.hcpc <- HCPC(res.pca, graph = FALSE, nb.par = 200,
                 nb.clust = 5)

fviz_dend(res.hcpc,
          k = 5,
          cex = 0.4,                     # Label size
          palette = "jco",               # Color palette see ?ggpubr::ggpar
          rect = TRUE, rect_fill = TRUE, # Add rectangle around groups
          rect_border = "jco",           # Rectangle color
          labels_track_height = 1     # Augment the room for labels
          )
```

```{r}
fviz_cluster(res.hcpc,            
             show.clust.cent = TRUE, # Show cluster centers
             palette = "jco",         # Color palette see ?ggpubr::ggpar
             ggtheme = theme_minimal(),
             main = "Factor map"
             )
```
```{r}
a<-unlist(res.hcpc$desc.ind$para)%>%as.data.frame()
a$Zone<-rownames(a)
a<-splitstackshape::concat.split(a, "Zone", sep = "[%.]", drop = TRUE)

a<-a%>%select("Zone" = "Zone_2","clust" = "Zone_1", "dist" = ".")
a$dist<-round(a$dist,2)

a1<-a%>%filter(clust == 1)%>%select(-"clust")

a2<-a%>%filter(clust == 2)%>%select(-"clust")

a3<-a%>%filter(clust == 3)%>%select(-"clust")

a4<-a%>%filter(clust == 4)%>%select(-"clust")

a5<-a%>%filter(clust == 5)%>%select(-"clust")

a3
```

```{r}
res.hcpc$data.clust

df<- df%>%left_join(res.hcpc$data.clust)
  

centroide<-select(df, -"Zone")%>%
  group_by(clust)%>%
  summarise_if(is.numeric, function(x) round(mean(x),1))
```




```{r, warning=FALSE, message=FALSE}

df$clust<-as.vector(df$clust)
df[df$clust == 1,]$clust<-"pays sous développés"
df[df$clust == 2,]$clust<-"pays en transition"
df[df$clust == 3,]$clust<-"proche orient"
df[df$clust == 4,]$clust<-"autres"
df[df$clust == 5,]$clust<-"occident"
df$clust<-as.factor(df$clust)

centroide<-select(df, -"Zone")%>%
  group_by(clust)%>%
  summarise_if(is.numeric, function(x) round(mean(x),1))%>%
  arrange(pib)
```

```{r}
###Je réalise un test de shapiro wilk sur chaque variable de la 
###table de base 

w<-ggplot(df, aes(prot))+
  geom_histogram(aes(y=..density..), bins = 30,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(prot)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())
       
shapiro.test(df$prot)

```

```{r}

x<-ggplot(df, aes(kcal))+
  geom_histogram(aes(y=..density..), bins = 30,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(kcal)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

shapiro.test(df$kcal)
```
```{r}

y<-ggplot(df, aes(pop_diff))+
  geom_histogram(aes(y=..density..), bins = 30,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(pop_diff)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

shapiro.test(df$pop_diff)
```
```{r}

z<-ggplot(df, aes(prot_ani_prct))+
  geom_histogram(aes(y=..density..), bins = 30,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(prot_ani_prct)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

shapiro.test(df$prot_ani_prct)
```
```{r}

v<-ggplot(df, aes(pib))+
  geom_histogram(aes(y=..density..), bins = 30,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(pib)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

shapiro.test(df$pib)

###On rejette l'hypothèse nulle au seuil de 1%
###Les variables retenues sont kcal et prot 
```
```{r}
grid.arrange(w,x,y,z,v, ncol=2, nrow = 3)
```
```{r, warning=FALSE, message=FALSE}
df_1<-df%>%filter(clust == "pays sous développés")%>%
  select(-"clust")

df_2<-df%>%filter(clust == "pays en transition")%>%
  select(-"clust")

df_3<-df%>%filter(clust == "proche orient")%>%
  select(-"clust")

df_4<-df%>%filter(clust == "autres")%>%
  select(-"clust")

df_5<-df%>%filter(clust == "occident")%>%
  select(-"clust")

```

```{r}
ggplot(df, aes(x = clust, y = kcal, fill = clust))+
  geom_boxplot()+ 
  theme(legend.position="none")+
  stat_summary(fun.y=mean, geom="point", shape=4, size=2)+
  scale_x_discrete(limits=c("pays sous développés",
                            "pays en transition",
                            "autres",
                            "proche orient",
                            "occident"))+ coord_flip()
```

```{r}
x1<-ggplot(filter(df, clust == "pays en transition"), aes(kcal))+
  geom_histogram(aes(y=..density..), bins = 10,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(kcal)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())


x2<-ggplot(filter(df, clust == "pays sous développés"), aes(kcal))+
  geom_histogram(aes(y=..density..), bins = 10,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(kcal)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

y1<-ggplot(filter(df, clust == "pays en transition"), aes(prot))+
  geom_histogram(aes(y=..density..), bins = 10,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(prot)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())


y2<-ggplot(filter(df, clust == "pays sous développés"), aes(prot))+
  geom_histogram(aes(y=..density..), bins = 10,
                 colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+
  geom_vline(aes(xintercept=mean(prot)),
            color="blue", linetype="dashed", size=1)+ 
  theme(axis.text.y = element_blank())

shapiro.test(filter(df, clust == "pays sous développés")$kcal)
shapiro.test(filter(df, clust == "pays en transition")$kcal)
shapiro.test(filter(df, clust == "pays sous développés")$prot)
shapiro.test(filter(df, clust == "pays en transition")$prot)
```

```{r}
grid.arrange(x1,x2,y1,y2, ncol=2, nrow = 3)
```

```{r}
###Test de fisher (variance)
var.test(df_1$kcal, df_2$kcal)
###p-value = 0.1093 on ne peut pas déterminer si les variances sont
###différentes
```
```{r}
t.test(df_1$kcal, df_2$kcal)
```

```{r}
ggplot(df, aes(x = clust, y = prot, fill = clust))+
  geom_boxplot()+ 
  theme(legend.position="none")+
  stat_summary(fun.y=mean, geom="point", shape=4, size=2)+
  scale_x_discrete(limits=c("pays sous développés",
                            "pays en transition",
                            "autres",
                            "proche orient",
                            "occident"))+coord_flip()
```
```{r}
###Test de fisher (variance)
var.test(df_1$prot, df_2$prot)
###p-value = 0.1093 on ne peut pas déterminer si les variances sont
###différentes
```
```{r}
t.test(df_1$prot, df_2$prot)
```

```{r}
df_table_5<-df_5

row.names(df_table_5)<-df_table_5$Zone
df_table_5<-select(df_table_5,"pib","pop_diff")

res.pca <- PCA(df_table_5, graph = FALSE)
```
```{r}
fviz_pca_var(res.pca,repel = TRUE)
```

```{r}
fviz_pca_ind(res.pca, col.ind = "x")
```


```{r}
pays_liste<-res.pca[["ind"]][["coord"]]%>%as.data.frame()
pays_liste$Zone<-rownames(pays_liste)
pays_liste<-pays_liste%>%select(Zone, Dim.1)%>%arrange(desc(Dim.1))
pays_liste

```





