---
title: "P5"
author: "brunop31"
date: "15/06/2020"
output: html_document
---
```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(DT)
library(reshape)
library(splitstackshape)
library(ggplot2)
library(scales)
library(ineq)
library(zoo)
library(cluster)
library(corrplot)
library(Hmisc)
library("ggpubr")
library(rstatix)
library(BioStatR)
library(reshape)
library(questionr)
library("FactoMineR")
library("factoextra")
library("gplots")
library(tidyr)
```

```{r}
pop_2010<-read.csv("pop_2010.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2010" = "Valeur")

pop_2018<-read.csv("pop_2018.csv", encoding = "UTF-8")%>%
  select("Zone", "pop2018" = "Valeur")

prot_ani_hab<-read.csv("prot_ani_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot_ani" = "Valeur")

prot_hab<-read.csv("prot_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "prot" = "Valeur")

kcal_hab<-read.csv("kcal_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "kcal" = "Valeur")

pib_hab<-read.csv("pib_habitant.csv", encoding = "UTF-8")%>%
  select("Zone", "pib" = "Valeur")
```

```{r}
df<-left_join(prot_ani_hab, prot_hab)%>%
  left_join(pop_2018)%>%left_join(pop_2010)%>%left_join(pib_hab)%>%
  left_join(kcal_hab)
```

