---
title: "code2_P8"
author: "brunop31"
date: "03/09/2020"
output: html_document
---

```{r, warning=FALSE}
library(ggplot2)
library(dplyr)
library(factoextra)
library(FactoMineR)
library(corrplot)
library(caret)
library(MASS)
library(car)
library(numbers)
library(randomForest)
library(nnet)

select<-dplyr::select

load("df_all")
load("df")
```

```{r}
###Recherche outlier

b = c()
c = c()

i = 1

for (i in 1 : 20) {

################# Fit the model Random forest###########################
model <- randomForest(Souche ~., df_all,
                      importance = TRUE)


b<-c(b, model$predicted%>%as.vector())

c<-c(c,df_all$Souche%>%as.vector())

i = i+1
}

error<-which(b != c)%>%mod(259)%>%as.data.frame()%>%
  rename("samp" = "." )%>%group_by(samp)%>%
  count()

big_error<-error$samp[which(error$n>19)]
```

```{r}
bad<-bad_sonde$Sonde[1:23]%>%as.vector()

df_out<-df_all%>%select(-bad)

bad_sonde$Sonde[1:23]%>%as.vector()

b1 = c()
b2 = c()
b3 = c()
c = c()

i = 1

for (i in 1 : 100) {

training.samples <- df_out$Souche %>%
  createDataPartition(p = 0.7, list = FALSE)

samp<-training.samples[,1]

train.data <- df_out[training.samples, ]

test.data <- df_out[-training.samples, ]

var_0<-which(apply(select(train.data,-"Souche"), 2, var)==0)%>%
  as.data.frame()%>%select(num = ".")%>%mutate(sonde = row.names(.))

train.data<-select(train.data, -var_0$sonde)
test.data<-select(test.data, -var_0$sonde)

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

df.transformed<-rbind(train.transformed,test.transformed)


################# Fit the model4 Random forest###########################
model1 <- randomForest(Souche ~., train.transformed)

b1<-c(b1, predict(model1, test.transformed)%>%as.vector())

###############nnet ##############################################
model2 <- nnet(Souche ~., train.transformed, size = 10,
               rang = 0.5,decay = 5e-60, maxit = 50,
              MaxNWts = 100000, abstol = 1)

predictions2<-model2 %>% predict(test.transformed)

x<-colnames(predictions2)[apply(predictions2, 1, which.max)]

b2<-c(b2, x)

################# mix model ############################################
predictions1<-predict(model1, test.transformed, type = "prob")

for (j in 1:nrow(test.transformed)) {
if(max(predictions1[j,])>0.3){
x[j]<-which.max(predictions1[j,])%>%names()}
else {x[j]<-which.max(predictions2[j,])%>%names()}
}

b3<-c(b3, x)
#######################################################################
c<-c(c,test.data$Souche%>%as.vector())

i = i+1
}


conf1<-confusionMatrix(b1%>%as.factor(), c%>%as.factor())
conf2<-confusionMatrix(b2%>%as.factor(), c%>%as.factor())
conf3<-confusionMatrix(b3%>%as.factor(), c%>%as.factor())

conf1
conf2
conf3
```
```{r}
model <- multinom(Souche ~., df_all[-big_error,])

predict(model, df_all[big_error,-1])
```
```{r}
model <- nnet(Souche ~., df_all[-big_error,], size = 50,
               rang = 0.5,decay = 5e-60, maxit = 50,
              MaxNWts = 100000, abstol = 1)

predictions<-model %>% predict(df_all[big_error,-1])

x<-colnames(predictions)[apply(predictions, 1, which.max)]

mean(x==df_all[big_error,]$Souche)

x
```
```{r}
model1 <- randomForest(Souche ~., train.transformed)

predictions1<-predict(model1, test.transformed, type = "prob")

model2 <- nnet(Souche ~., train.transformed, size = 50,
               rang = 0.5,decay = 5e-60, maxit = 50,
              MaxNWts = 100000, abstol = 1)

predictions2<-model2 %>% predict(test.transformed)

for (i in 1:nrow(test.transformed)) {
if(max(predictions1[i,])>0.6){
x[i]<-which.max(predictions1[i,])%>%names()}
else {x[i]<-which.max(predictions2[i,])%>%names()}
}

mean(x==test.transformed$Souche)
```

```{r}
model <- randomForest(Souche ~., df_all,
                      importance = TRUE)

imp<-importance(model)%>%as.data.frame()

par(mfrow = c(3,4))

for (i in 1:11) {
  names10<-imp%>%arrange(desc(imp[,i]))%>%row.names()%>%.[1:10]
  imp10<-imp%>%arrange(desc(imp[,i]))%>%.[1:10,i]%>%round(3)
  plot(imp10,type="h",ylab="Importance",xlab="Sondes",xaxt = "n")
  title(main = colnames(imp)[i], pch=16, cex.main=1, line = 0.5)
  points(imp10,pch=20)
  axis(1,at=1:10,labels=names10,cex.axis=1,las=3)
}
```

```{r}

confusionMatrix(predict(model), df_all$Souche)

imp_sum<-apply(imp, 2, sum)

imp_sum
```

```{r}
df_all <- df_all[,-nearZeroVar(df_all, uniqueCut = 0)]

dfDescr<-df_all%>%select(-"Souche")
dfClass<-df_all$Souche

set.seed(1)  
inTrain <- createDataPartition(dfClass, p = .75, list = FALSE)[,1]

train <- dfDescr[ inTrain, ]
test  <- dfDescr[-inTrain, ]
trainClass <- dfClass[ inTrain]
testClass  <- dfClass[-inTrain]

rfProfile <- rfe(train, trainClass,
                  sizes = c(30:68),
                  rfeControl = rfeControl(functions = rfFuncs,
                                          method = "cv"))
plot(rfProfile, type = c("o", "g"))
```


```{r}
df_all<-read.csv(
  "donnee_dendris.csv",
  encoding = "UTF-8", sep = ",", dec = ".")

#On supprime la colonne qui donne le numéro de ligne
df_all<-df_all[,-1]

#On regarde s'il manque des données
head(which(is.na(df_all), arr.ind = TRUE))

#On remplace quand c'est possibme par la médiane de samp du même groupe
df_all[195,11]<-median(filter(df_all, Souche == "Spn")[,11],na.rm = TRUE)

#On supprime quand ce n'est pas possible
df_all<-df_all[-182,]

#On réorganise les lignes
row.names(df_all)<-1:263

#On a plus de valeurs manquantes
head(which(is.na(df_all), arr.ind = TRUE))

###on supprime les sondes disfonctionnelle
sonde_force<-apply(df_all%>%select(-"Souche"), 2, sum)%>%as.data.frame()%>%
  rename("sum" = ".")

sonde_force$col<-2:69

x<-which(df_all != 0, arr.ind = TRUE)%>%
  as.data.frame()%>%group_by(col)%>%count()%>%
  full_join(data.frame(col = 1:69))

x<-x[-1,]  
x[is.na(x)]<-0

df_all<-df_all[-c(95,96,263),]

df_all <- df_all[,-nearZeroVar(df_all, uniqueCut = 0)]

dfDescr<-df_all%>%select(-"Souche")
dfClass<-df_all$Souche
```

```{r}
bonne_sonde<-c()

for (i in 1:10) {
set.seed(i)  
inTrain <- createDataPartition(dfClass, p = .75, list = FALSE)[,1]

train <- dfDescr[ inTrain, ]
test  <- dfDescr[-inTrain, ]
trainClass <- dfClass[ inTrain]
testClass  <- dfClass[-inTrain]

rfProfile <- rfe(train, trainClass,
                  sizes = c(30:68),
                  rfeControl = rfeControl(functions = rfFuncs,
                                          method = "cv"))

bonne_sonde<-c(bonne_sonde, rfProfile$optVariables)
}

a<-bonne_sonde%>%as.data.frame()%>%rename("Sonde" = ".")%>%
  group_by(Sonde)%>%count()

c<-colnames(df_all[,2:ncol(df_all)])%>%as.data.frame()%>%
  rename("Sonde" = ".")

b<-full_join(c,a)
b[is.na(b)]<-0

bad_sonde<-b%>%arrange(n)

```

```{r}
set.seed(1)
######################### Random Forest only########################
#bad<-(bad_sonde%>%filter(n < 3))$Sonde%>%as.vector()

df_out<-df_log

b1 = c()
c = c()

i = 1

for (i in 1 : 1000) {

training.samples <- df_out$Souche %>%
  createDataPartition(p = 0.7, list = FALSE)

samp<-training.samples[,1]

train.data <- df_out[training.samples, ]

test.data <- df_out[-training.samples, ]

var_0<-which(apply(select(train.data,-"Souche"), 2, var)==0)%>%
  as.data.frame()%>%select(num = ".")%>%mutate(sonde = row.names(.))

train.data<-select(train.data, -var_0$sonde)
test.data<-select(test.data, -var_0$sonde)

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

df.transformed<-rbind(train.transformed,test.transformed)


################# Fit the model4 Random forest###########################
model1 <- randomForest(Souche ~., train.transformed,
                       cutoff = c(0.1,0.12,0.09,0.06,0.1,
                                  0.08,0.1,0.11,0.08,
                                  0.055,0.1), mtry = 10,
                       ntree = 1500)

b1<-c(b1, predict(model1, test.transformed)%>%as.vector())


#######################################################################
c<-c(c,test.data$Souche%>%as.vector())

i = i+1
}

conf1<-confusionMatrix(b1%>%as.factor(), c%>%as.factor())

conf1
##########################################################################
```

```{r}
dfDescr<-df_out%>%select(-"Souche")
dfClass<-df_out$Souche

bonne_sonde<-c()

for (i in 1:10) {
set.seed(i)  
inTrain <- createDataPartition(dfClass, p = .75, list = FALSE)[,1]

train <- dfDescr[ inTrain, ]
test  <- dfDescr[-inTrain, ]
trainClass <- dfClass[ inTrain]
testClass  <- dfClass[-inTrain]

rfProfile <- rfe(train, trainClass,
                  sizes = c(30:68),
                  rfeControl = rfeControl(functions = rfFuncs,
                                          method = "cv"))

plot(rfProfile, type = c("o", "g"))

bonne_sonde<-c(bonne_sonde, rfProfile$optVariables)
}

a2<-bonne_sonde%>%as.data.frame()%>%rename("Sonde" = ".")%>%
  group_by(Sonde)%>%count()

c2<-colnames(df_out[,2:ncol(df_out)])%>%as.data.frame()%>%
  rename("Sonde" = ".")

b2<-full_join(c2,a2)
b2[is.na(b2)]<-0

bad_sonde2<-b2%>%arrange(n)
```

```{r}
######################### Random Forest only########################
bad2<-(bad_sonde2%>%filter(n < 9))$Sonde%>%as.vector()

df_out2<-df_out%>%select(-bad2)

b1 = c()
c = c()

i = 1

for (i in 1 : 1000) {

training.samples <- df_out2$Souche %>%
  createDataPartition(p = 0.7, list = FALSE)

samp<-training.samples[,1]

train.data <- df_out2[training.samples, ]

test.data <- df_out2[-training.samples, ]

var_0<-which(apply(select(train.data,-"Souche"), 2, var)==0)%>%
  as.data.frame()%>%select(num = ".")%>%mutate(sonde = row.names(.))

train.data<-select(train.data, -var_0$sonde)
test.data<-select(test.data, -var_0$sonde)

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

df.transformed<-rbind(train.transformed,test.transformed)


################# Fit the model4 Random forest###########################
model1 <- randomForest(Souche ~., train.transformed, mtry = 10,
                       ntree = 500)

b1<-c(b1, predict(model1, test.transformed)%>%as.vector())


#######################################################################
c<-c(c,test.data$Souche%>%as.vector())

i = i+1
}

conf1<-confusionMatrix(b1%>%as.factor(), c%>%as.factor())

conf1
##########################################################################
```

```{r}
dfDescr<-df_out2%>%select(-"Souche")
dfClass<-df_out2$Souche

inTrain <- createDataPartition(dfClass, p = .75, list = FALSE)[,1]

train <- dfDescr[ inTrain, ]
test  <- dfDescr[-inTrain, ]
trainClass <- dfClass[ inTrain]
testClass  <- dfClass[-inTrain]

rfProfile <- rfe(train, trainClass,
                  sizes = c(22:33),
                  rfeControl = rfeControl(functions = rfFuncs,
                                          method = "cv"))

plot(rfProfile, type = c("o", "g"))
```

```{r}
rfProfile <- rfe(Souche~., df_all,
                 size = c(29),
                 maximize = FALSE,
                 rfeControl = rfeControl(
                    functions = rfFuncs, method = "repeatedcv",
                    repeats = 5)
                 )

plot(rfProfile, type = c("o", "g"))

rfProfile$optVariables
```


```{r}
######################### Random Forest only########################
df_normal <- df_all[,-nearZeroVar(df_all)]
df_normal <- df_all[, -findCorrelation(cor(df_all%>%select(-"Souche")), .8)]

b1 = c()
c = c()

i = 1

for (i in 1 : 1000) {

training.samples <- df_normal$Souche %>%
  createDataPartition(p = 0.7, list = FALSE)

samp<-training.samples[,1]

train.data <- df_normal[training.samples, ]

test.data <- df_normal[-training.samples, ]

var_0<-which(apply(select(train.data,-"Souche"), 2, var)==0)%>%
  as.data.frame()%>%select(num = ".")%>%mutate(sonde = row.names(.))

train.data<-select(train.data, -var_0$sonde)
test.data<-select(test.data, -var_0$sonde)

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

df.transformed<-rbind(train.transformed,test.transformed)


################# Fit the model4 Random forest###########################
model1 <- randomForest(Souche ~., train.transformed)

b1<-c(b1, predict(model1, test.transformed)%>%as.vector())


#######################################################################
c<-c(c,test.data$Souche%>%as.vector())

i = i+1
}

conf1<-confusionMatrix(b1%>%as.factor(), c%>%as.factor())

conf1
##########################################################################

```


```{r}
x<-df_out2[,2:length(df_out2)]%>%colnames()

y<-df_normal[,2:length(df_normal)]%>%colnames()

x %in% y
```

```{r}
######################### Random Forest only########################
b1 = c()
c = c()

i = 1

for (i in 1 : 100) {

training.samples <- df_log$Souche %>%
  createDataPartition(p = 0.7, list = FALSE)

samp<-training.samples[,1]

train.data <- df_log[training.samples, ]

test.data <- df_log[-training.samples, ]

var_0<-which(apply(select(train.data,-"Souche"), 2, var)==0)%>%
  as.data.frame()%>%select(num = ".")%>%mutate(sonde = row.names(.))

train.data<-select(train.data, -var_0$sonde)
test.data<-select(test.data, -var_0$sonde)

# Estimate preprocessing parameters
preproc.param <- train.data %>% 
  preProcess(method = c("center", "scale"))
# Transform the data using the estimated parameters
train.transformed <- preproc.param %>% predict(train.data)
test.transformed <- preproc.param %>% predict(test.data)

df.transformed<-rbind(train.transformed,test.transformed)


################# Fit the model4 Random forest###########################
model1 <- klaR::rda(Souche ~., train.transformed)

b1<-c(b1, predict(model1, test.transformed)%>%as.vector())

#######################################################################
c<-c(c,test.data$Souche%>%as.vector())

i = i+1
}

conf1<-confusionMatrix(b1%>%as.factor(), c%>%as.factor())

conf1
##########################################################################

```


```{r}
dfDescr<-df_out2%>%select(-"Souche")
dfClass<-df_out2$Souche

tune<-tuneRF(dfDescr, dfClass, stepFactor=1.3,trace=TRUE, plot=TRUE,
             doBest=TRUE, improve = 0.001, mtryStart = 7
             )
```




