---
title: "Untitled"
author: "brunop31"
date: "15/09/2020"
output: html_document
---
```{r}
df_out<-read.csv(
  "samples.csv",
  encoding = "UTF-8", sep = ";", dec = ",")%>%select(-"X")

df_out<-df_out%>%select(-c("X65","X141"))

write.csv(df_out, "echantillon.csv")

df_out$Souche<-c()
```

```{r}
df_out<-read.csv("echantillon.csv",encoding = "UTF-8", sep = ",",dec = ".")%>%
   select(-c("X","X65","X141"))

dfs_out<-df_out%>%select(-"Souche")
dfs_all<-select(df_all, -"Souche")

for (i in 1:158) {
  
dfs_out[42 + i,]<-dfs_all[sample(1:nrow(dfs_out), 2), ]%>%
  apply(2, function(x) sum(x)/2)%>%round()
}


```

```{r}
################# Fit the model3 Random forest########################
model3 <- randomForest(Souche ~., df_all, mtry = 10,
                       ntree = 1500)

b3<-predict(model3, dfs_out)%>%as.vector()

###############Fit the model4 nnet #################################
model4 <- nnet(Souche ~., df_all, size = 50,
               rang = 0.5,decay = 5e-60, maxit = 50,
              MaxNWts = 100000, abstol = 1)

predictions<-model4 %>% predict(df_test)

x<-colnames(predictions)[apply(predictions, 1, which.max)]

b4<-x

#################Fit the model5 multinom ##########################
model5 <- multinom(Souche ~., df_all)

b5<-predict(model5, df_test)%>%as.vector()

#################################################################

model <- lda(Souche~., data = df_all)
# Make predictions
predictions <- model %>% predict(df_test)

b<-predictions$class%>%as.vector()

df_test$Souche[1:80]<-b7[1:80]
df_test$Souche[81:110]<-b4[81:110]
df_test$Souche[111:160]<-b3[111:160]
df_test$Souche[161:200]<-b[161:200]

df_out<-dfs_out%>%relocate("Souche")

write.csv(df_test, "echantillon.csv")

df_test<-read.csv("echantillon.csv",encoding = "UTF-8",
                  sep = ",",dec = ".")%>%select(-"X")


```

```{r}
write.csv(df_all, "donnee_dendris.csv")
```
```{r}
df_type<-df_allume[,3:68]%>%apply(2,sum)%>%as.data.frame()%>%
  rename("sum" = ".")

x<-df_type%>%filter(sum<=5 & sum>=0)%>%row.names()

speci<-df_allume[,x]%>%.[,apply(.,2,max) <= 0.7]

speci%>%colnames()
```
