---
title: "outlier"
author: "brunop31"
date: "03/09/2020"
output: html_document
---
```{r}
library(ggplot2)
library(dplyr)
library(factoextra)
library(FactoMineR)
library(corrplot)
library(caret)
library(MASS)
library(car)
library(numbers)

select<-dplyr::select

df_all<-read.csv(
  "donnee_dendris.csv",
  encoding = "UTF-8", sep = ",", dec = ".")

#On supprime la colonne qui donne le numéro de ligne
df_all<-df_all[,-1]

#On regarde s'il manque des données
head(which(is.na(df_all), arr.ind = TRUE))

#On remplace quand c'est possibme par la médiane de samp du même groupe
df_all[195,11]<-median(filter(df_all, Souche == "Spn")[,11],na.rm = TRUE)

#On supprime quand ce n'est pas possible
df_all<-df_all[-182,]

#On réorganise les lignes
row.names(df_all)<-1:263

#On a plus de valeurs manquantes
head(which(is.na(df_all), arr.ind = TRUE))

###on supprime les sondes disfonctionnelle
sonde_force<-apply(df_all%>%select(-"Souche"), 2, sum)%>%as.data.frame()%>%
  rename("sum" = ".")

sonde_force$col<-2:69

x<-which(df_all != 0, arr.ind = TRUE)%>%
  as.data.frame()%>%group_by(col)%>%count()%>%
  full_join(data.frame(col = 1:69))

x<-x[-1,]  
x[is.na(x)]<-0

#Après examen des sondes j'ai supprimé les pire(j'ai préféré enlever 4 que 5)
df_all<-df_all[,-c(35,62,3,24,2,17,27,30,31,4)]


#Test de normalité
pvalue<-c()
sonde<-c()
for (i in 2:36) {
 x<-shapiro.test(df_all[,i])
  pvalue[i-1]<-x$p.value
  sonde[i-1]<-colnames(df_all)[i]
}

#Les variables ne sont clairement pas normalement distribuées

gauss<-cbind(sonde,pvalue)%>%data.frame()
gauss$pvalue<-gauss$pvalue%>%as.vector()%>%as.numeric()

#J'analyse mes sondes
ggplot(df_all, aes(Souche, df_all$X7, fill = Souche, colour = Souche)) +
  geom_jitter(width=0.25)+
        geom_boxplot(alpha=0.5, outlier.shape=NA,)+  
        xlab(label = "Type of car") +
        ylab(label = "Highway miles per gallon") +
        theme(axis.text.x = element_text(angle=30, hjust=1, vjust=1))+
        theme(legend.position="none")+
        theme_classic()+
        ggtitle("Boxplot avec les observations")

#Je fais un tableau recap de mes sonde (mediane nombre de sonde allumé)

df_median<-df_all%>%group_by(Souche)%>%summarise_all(median)

df_01<-df_all%>%select(-"Souche")
df_01[df_01!=0]<-1
df_01<-cbind(df_all$Souche, df_01)%>%rename("Souche" = "df_all$Souche")

df_allume<-df_01%>%group_by(Souche)%>%summarise_all(mean)
df_allume[,-1]<-df_allume[,-1]%>%round(2)
sum<-apply(df_allume%>%select(-"Souche"),1,sum)
df_allume<-cbind(sum,df_allume)

#On supprime la sonde X14 et la sonde X108 spécifique à aucune souche
df_all<-df_all%>%select(-c("X14","X108","X81"))

#Les sondes X24,X25,X26,X81,X170 sont spécifique au mpn ne pas les enlever
df_all<-df_all[-c(95,96,263),]
```


```{r}
#sonde la plus spécifique Spn (mauvaise)
#df_all$X174<-df_all$X31
#df_all$X175<-df_all$X31
#df_all$X176<-df_all$X31
#df_all$X177<-df_all$X31

#sonde la plus spécifique Spn (mauvaise)
#df_all$X178<-df_all$X102
#df_all$X179<-df_all$X102
#df_all$X180<-df_all$X102
#df_all$X181<-df_all$X102

#sonde la plus spécifique Ssp (mauvaise)
#df_all$X182<-df_all$X32
#df_all$X183<-df_all$X32
#df_all$X184<-df_all$X32

#sonde la plus spécifique Bp (mauvaise)
#df_all$X185<-df_all$X7
#df_all$X186<-df_all$X7
#df_all$X187<-df_all$X7

#sonde la plus spécifique pa (bonne)
#df_all$X191<-df_all$X38
#df_all$X192<-df_all$X38
#df_all$X193<-df_all$X38


row.names(df_all)<-1:260
#Je fais un tableau recap de mes sonde (mediane nombre de sonde allumé)
df_median<-df_all%>%group_by(Souche)%>%summarise_all(median)



df_01<-df_all%>%select(-"Souche")
df_01[df_01!=0]<-1
df_01<-cbind(df_all$Souche, df_01)%>%rename("Souche" = "df_all$Souche")

df_allume2<-df_01%>%group_by(Souche)%>%summarise_all(mean)
df_allume2[,-1]<-df_allume2[,-1]%>%round(2)
sum<-apply(df_allume2%>%select(-"Souche"),1,sum)
df_allume2<-cbind(sum,df_allume2)

df_allume<-df_01%>%group_by(Souche)%>%summarise_all(median)
df_allume[,-1]<-df_allume[,-1]%>%round(2)
sum<-apply(df_allume%>%select(-"Souche"),1,sum)
df_allume<-cbind(sum,df_allume)

which(df_allume==0.5, arr.ind = TRUE )
```

```{r}
df_allume2<-df_allume2[,-c(4,20,39,40,44,50)]
df_all<-df_all[,-c(4,20,39,40,44,50)]
```


```{r}
outlier<-c()
for (i in 1:nrow(df_all)) {
j<-df_all$Souche[i]%>%as.numeric()

x<-((df_all[i,-1])!=0)%>%as.numeric()*2-1

z<-sum((df_allume2[j,-c(1:2)]*3-1)*x)

outlier<-c(outlier,z)
}

outlier<-outlier%>%as.data.frame()%>%cbind(df_all$Souche,.)%>%
  rename("Souche" = "df_all$Souche")

mean<-outlier%>%group_by(Souche)%>%summarise(mean = mean(.))

outlier<-full_join(outlier,mean)%>%mutate(score = ./mean)
```

```{r}
algo<-data.frame()
for (i in 1:nrow(df_all)) {
  
x<-((df_all[i,-1])!=0)%>%as.numeric()*2-1

  for (j in 1:11) {
  z<-sum((df_allume2[j,-c(1:2)]*3-1)*x)/mean$mean[j]

algo[i,j]<-z
}
}


colnames(algo)<-levels(df_all$Souche)

x<-colnames(algo)[apply(algo, 1, which.max)]

mean(df_all$Souche==x)

confusionMatrix(x%>%as.factor(),df_all$Souche%>%as.factor())
```

