---
title: "Untitled"
author: "brunop31"
date: "06/04/2020"
output: html_document
---
```{r}
library(dplyr)
library(DT)
library(reshape)
library(splitstackshape)
library(ggplot2)
library(scales)
library(ineq)
library(zoo)
library(cluster)
library(corrplot)
library(Hmisc)
library("ggpubr")
library(rstatix)
library(BioStatR)
library(reshape)
library(questionr)
library("FactoMineR")
library("factoextra")
library("gplots")

```

```{r}
products<-read.csv("products.csv", encoding = "UTF-8")%>%
  filter(id_prod != "T_0")

customers<-read.csv("customers.csv", encoding = "UTF-8")%>%
  filter(!(client_id %in% c("ct_1","ct_0")))

transactions<-read.csv("transactions.csv", encoding = "UTF-8")%>%
  filter(id_prod != "T_0")

products$categ<-factor(products$categ)

sapply(products,function(x) sum(is.na(x)))
sapply(customers,function(x) sum(is.na(x)))
sapply(transactions,function(x) sum(is.na(x)))

isTRUE(nrow(distinct(customers)) == nrow(customers))
isTRUE(nrow(distinct(transactions)) == nrow(transactions))
isTRUE(nrow(distinct(products)) == nrow(products))


```

```{r}
price<-inner_join(transactions, products)%>%
  inner_join(customers)%>%
  mutate(age = 2022 - birth)

x<-price%>%filter(age<=30 | age >50)
y<-price%>%filter(age>30 & age <= 50)

x$categ_age_bis<-"[16, 30]U]50, 100]"
y$categ_age_bis<-"]30, 50]"


price<-rbind(x,y)

price$categ_age_bis <- factor(price$categ_age_bis, levels = c(
  "[16, 30]U]50, 100]", "]30, 50]" ))

x<-price%>%filter(age<=30)
y<-price%>%filter(age>30 & age<=50)
z<-price%>%filter(age>50)

x$categ_age<-"jeune"
y$categ_age<-"moyen"
z$categ_age<-"senior"

price<-rbind(x,y,z)

price$categ_age <- factor(price$categ_age, levels = c(
  "jeune", "moyen", "senior"))

price$date<-as.Date(price$date)

price$age_sex<- paste(price$categ_age, price$sex, sep="_")

check_possible_primary_key(price, session_id, id_prod, date)

nbre_date<-price%>%group_by(date, id_prod)%>%count()%>%
  inner_join(select(products, id_prod, price))%>%
  mutate(n_price = n*price)%>%
  group_by(date)%>%summarise(price = sum(n_price), n = sum(n))

nbre_date_categ<-price%>%group_by(date, id_prod)%>%count()%>%
  inner_join(select(products, id_prod, price, categ))%>%
  mutate(n_price = n*price)%>%
  group_by(date, categ)%>%summarise(price = sum(n_price), n = sum(n))

nbre_date_categ_age<-price%>%group_by(date, id_prod,categ_age)%>%count()%>%
  inner_join(select(products, id_prod, price))%>%
  mutate(n_price = n*price)%>%
  group_by(date, categ_age)%>%summarise(price = sum(n_price), n = sum(n))

nbre_prdt_loue<-price%>%group_by(id_prod)%>%count()
           
nbre_prdt_loue<-inner_join(nbre_prdt_loue, products)%>%
  mutate(n_price = n*price)


nbre_date$date<-as.Date(nbre_date$date)

cor(as.numeric(price$categ), as.numeric(price$categ_age))

cor(as.numeric(price$categ), as.numeric(price$sex))

nbre_0<-nrow(filter(price, categ == 0))
nbre_1<-nrow(filter(price, categ == 1))
nbre_2<-nrow(filter(price, categ == 2))

summary(filter(price, categ == 2)$price)
summary(price$price)
summary(products$price)

price$categ<-as.factor(price$categ)
```

```{r}
p <- ggplot(price, aes(x = categ, y = age)) + geom_boxplot()
p+ stat_summary(fun.y=mean, geom="point", shape=23, size=1)
```

```{r}
g <- ggplot(price, aes(x = categ, y = price)) + geom_boxplot()
g+ stat_summary(fun.y=mean, geom="point", shape=23, size=1)
```

```{r}
h<-ggplot(price, aes(x = price, y = age, group = categ)) +
  geom_point(aes(shape=categ, color=categ), alpha = 0.1,
             position = position_jitter(width = 0.5, height = 0.5))+ geom_smooth(aes(color = categ),fullrange = FALSE)
h
```

```{r}

plot(nbre_date$date, nbre_date$n, type = "l", xlab = "date",
ylab = "nombre de livre", col = "royalblue3")
```
```{r}
plot(nbre_date$date, nbre_date$price, type = "l", xlab = "date",
ylab = "gain", col = "royalblue3")
```
```{r}
nbre_date_categ<-arrange(nbre_date_categ, categ)

nbre_date_categ$roll7 = rollmean(nbre_date_categ$price, 7, na.pad=TRUE, align = "right")
```
```{r}
ggplot(nbre_date_categ, aes(date, roll7)) +
  geom_line(aes(colour = categ))+
  scale_x_date(breaks = date_breaks("months"), 
               limits = c(as.Date("2021-03-07"),NA),
  labels = date_format("%b"))
```

```{r}
nbre_date_categ_age<-arrange(nbre_date_categ_age, categ_age)

nbre_date_categ_age$roll7 = rollmean(
  nbre_date_categ_age$price, 7, align = "right", na.pad=TRUE)


ggplot(nbre_date_categ_age, aes(date, roll7)) +
  geom_line(aes(colour = categ_age))+
  scale_x_date(breaks = date_breaks("months"), 
               limits = c(as.Date("2021-03-07"),NA),
  labels = date_format("%b"))

```

```{r}
plot(Lc(nbre_prdt_loue$n_price))
```
```{r}
ineq(nbre_prdt_loue$n_price,type="Gini")
```

```{r}
plot(Lc(nbre_prdt_loue$n))
```
```{r}
ineq(nbre_prdt_loue$n,type="Gini")
```


```{r}
categ_age<-price%>%group_by(categ_age, categ)%>%
  summarise(sum_price = sum(price))

categ_age$sum_price<-categ_age$sum_price/1000

ggplot(categ_age, aes(x = categ_age, y = sum_price)) + 
  geom_bar(aes(color = categ, fill = categ),
                 stat = "identity", width = 0.5) +
  xlab("Catégories d'âges") + ylab("Dépense (en milliers d'euros)")
```
```{r}
categ_age_sex<-price%>%group_by(categ_age, sex, categ)%>%
  summarise(sum_price = sum(price))

categ_age_sex<-categ_age_sex%>%
  transmute(
    age_sex = 
      paste(categ_age, sex, sep="_"),
    categ = categ,
    sum_price = sum_price)

a<-price%>%
  group_by(client_id, age_sex)%>%count()%>%
  group_by(age_sex)%>%count()

categ_age_sex$n_sex_age<-
  c(rep(a$n[1], 3),rep(a$n[2], 3),rep(a$n[3], 3),
     rep(a$n[4], 3),rep(a$n[5], 3),rep(a$n[6], 3))

categ_age_sex$sum_price_n<-
  categ_age_sex$sum_price/categ_age_sex$n_sex_age

            

ggplot(categ_age_sex, aes(x = age_sex, y = sum_price_n)) + 
  geom_bar(aes(color = categ, fill = categ),
                 stat = "identity", width = 0.5) +
  xlab("Catégories") + 
  ylab("Dépense moyenne par client")
```

```{r}
categ_sex<-price%>%group_by(sex, categ)%>%
  summarise(sum_price = sum(price))

categ_sex$sum_price<-categ_sex$sum_price/1000

ggplot(categ_sex, aes(x = sex, y = sum_price)) + 
  geom_bar(aes(color = categ, fill = categ),
                 stat = "identity", width = 0.5) +
  xlab("sexe") + ylab("Dépense (en milliers d'euros)")
```



```{r}
categ_max<-price%>%group_by(client_id, categ, age, categ_age)%>%count()%>%
  group_by(client_id)%>%
  filter(n == max(n))

cor.test(as.numeric(categ_max$categ_age), as.numeric(categ_max$categ))
cor.test(price$age, as.numeric(price$categ))

client<-select(price, age, client_id, session_id)%>%distinct()%>%
  group_by(client_id, age)%>%count()%>%ungroup()%>%
  transmute(client_id = client_id,
            age = age,
            frequence = n/12)

  
client$panier_moyen<-price%>%group_by(client_id)%>%count()%>%
  .$n/(client$frequence*12)

client$montant_total<-price%>%group_by(client_id)%>%
  summarise(sum_price = sum(price))%>%.$sum_price

client<-inner_join(client, distinct(select(
  price, client_id, categ_age, sex, categ_age_bis )),
                   by = "client_id")


client$categ_age<-as.numeric(client$categ_age)
client$categ_age_bis<-as.numeric(client$categ_age_bis)
client$sex<-as.numeric(client$sex)
```

```{r}
plot(Lc(client$montant_total))
```
```{r}
ineq(client$montant_total,type="Gini")
```
```{r}
client_cor<-select(client, -"client_id", -"sex", -"categ_age")

cormat <- cor(client_cor, method = "spearman")

p.mat <- cor.mtest(client_cor)$p

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD",
                          "#4477AA"))

corrplot(cormat, method = "color", col = col(200),
         type = "upper", order = "AOE", number.cex = .7,
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "black", tl.srt = 90, # Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)

t.test(data = client, age ~ sex)
```
```{r}
client_cor_f<-select(filter(client, sex == 1),
                     -"client_id", -"sex", -"categ_age")

p.mat2 <- cor.mtest(client_cor_f)$p

cormat_f <- cor(client_cor_f, method = "spearman")

corrplot(cormat_f, method = "color", col = col(200),
         type = "upper", order = "AOE", number.cex = .7,
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "black", tl.srt = 90, # Text label color and rotation
         # Combine with significance
         p.mat = p.mat2, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)
```
```{r}
client_cor_m<-select(filter(client, sex == 2),
                     -"client_id", -"sex", -"categ_age")

p.mat3 <- cor.mtest(client_cor_m)$p

cormat_m <- cor(client_cor_m, method = "spearman")

corrplot(cormat_m, method = "color", col = col(200),
         type = "upper", order = "AOE", number.cex = .7,
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "black", tl.srt = 90, # Text label color and rotation
         # Combine with significance
         p.mat = p.mat3, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)
```



```{r}
client%>%filter(montant_total < 10000)%>%
ggplot(aes(x = panier_moyen, y = age)) + geom_point()
```

```{r}
client%>%filter(montant_total < 10000)%>%
ggplot(aes(x = montant_total, y = age)) + geom_point()
```

```{r}
client%>%filter(montant_total < 10000)%>%
ggplot(aes(x = frequence, y = age)) + geom_point()
```
```{r}
contingence_table<-table(price$sex, price$categ)

ct<-as.vector(contingence_table)

balloonplot(t(contingence_table), xlab = "", ylab = "",
            label = FALSE, show.margins = FALSE)

chisq.test(contingence_table)

cramer.v(contingence_table)
```
```{r}
variance_table<-table(price$age, price$categ)

client_age<-client%>%group_by(age)%>%count()

variance_table_chi2<-
  table(filter(price, age < 91)$age,
        filter(price, age < 91)$categ)

cramer.v(variance_table_chi2)
chisq.test(variance_table_chi2)

cramer.v(table(price$categ_age, price$categ))

library ("FactoMineR")
res.ca <- CA (variance_table, graph = FALSE)
library ("factoextra")
eig.val <- get_eigenvalue (res.ca)
eig.val
fviz_ca_biplot (res.ca, repel = TRUE)
fviz_ca_row(res.ca, repel = TRUE)
```
```{r}
b<-table(price$age, price$categ)

cramer.v(b)

res.ca <- CA (b, graph = FALSE)
eig.val <- get_eigenvalue (res.ca)
eig.val
fviz_ca_row(res.ca, repel = TRUE)
fviz_ca_biplot (res.ca, repel = TRUE)
```
```{r}
a<-table(
  filter(price, age_sex %in%c("jeune_f","jeune_m"))$age_sex,
  filter(price, age_sex %in% c("jeune_f","jeune_m"))$categ)

cramer.v(a)
```

```{r}
res.aov <- aov(as.numeric(age) ~ categ, data = price)
summary(res.aov)

# Effect size
eta_squared(res.aov)
```




