---
title: "Untitled"
author: "brunop31"
date: "23/06/2020"
output: html_document
---

```{r}
df<-data.frame("age"= c(1:3),"poids" = c(60, 17, 50))

res.pca<-PCA(df, graph = TRUE, scale.unit = FALSE)

res.pca2<-PCA(dfs, graph = TRUE, scale.unit = TRUE)

t(apply(res.pca$var$coord, 1, function(x) {x/sqrt(res.pca$eig[,1])}))

dfa<-t((t(df)-  colMeans(df))/apply(df, 2, sd))



dfs<-scale(df)

colMeans(df)  
  
pca2<-prcomp(df, scale = TRUE)

res.pca$ind$coord[,1]/(dfs[,"age"] - dfs[,"poids"])
res.pca2$ind$coord[,1]/(dfs[,"age"] - dfs[,"poids"])


pca2$x[,1]/(dfs[,"age"] - dfs[,"poids"])
pca2$x[,2]/(dfs[,"age"] + dfs[,"poids"])

res.pca$ind$coord/pca2$x



-1.732051/2

sqrt(0.8273268)

scale(c(0.9095751,0.4155396))

scale(c(0.9095751, -0.9095751, 0.4155396, -0.4155396))


```

```{r}
fviz_pca_var(res.pca, geom.ind = "point")
```
```{r}
fviz_pca_var(pca2, geom.ind = "point")
```

```{r}
df<-data.frame("age"= c(1:3),"poids" = c(60, 10 ,40))

res.pca<-PCA(df, graph = TRUE, scale.unit = FALSE)

```

```{r}
scale(scale(-0.009893006*df[,"age"], scale = F) + 
  scale(0.999951063*df[,"poids"], scale = F))


-0.3248746*df[,"age"] + 20.5480433*df[,"poids"]

res.pca$ind$coord

res.pca$var$coord
```
```{r}

```

